dataset:
  dataset_names: 
    #- MMLU_biology
    #- MMLU_anatomy
    #- MMLU_medicine
    #- MMLU_clinical
    #- PubMedQA
    - MedMCQA
    #- HaluEval

model: ChatGLM

generation:
  few_shot: 0 # number of shots 
  CoT: True # True/ False 
  k_self_consistency: 0 # number of self-consistency
  top_p: 0.9
  temperature: 1
  batch_size: 3

response:
  
  chosen_datasets:
  # Uncomment the datasets you would like to shorten

   MMLU_biology: "responses/{{ model }}/{{ fs }}-shot/MMLU_biology" 
   #MMLU_anatomy: "responses/{{ model }}/{{ fs }}-shot/MMLU_anatomy" 
   #MMLU_medicine: "responses/{{ model }}/{{ fs }}-shot/MMLU_medicine" 
   #MMLU_clinical: "responses/{{ model }}/{{ fs }}-shot/MMLU_clinical"
   #PubMedQA: "responses/{{ model }}/{{ fs }}-shot/PubMedQA"
   #MedMCQA: "responses/{{ model }}/{{ fs }}-shot/MedMCQA"
   #HaluEval: "responses/{{ model }}/{{ fs }}-shot/HaluEval"

  shortened_save_path: null
shortened: shortened/Med42/0-shot
