dataset:
  dataset_names: 
    #- MMLU_biology
    #- MMLU_anatomy
    #- MMLU_medicine
    #- MMLU_clinical
    #- PubMedQA
    - MedMCQA
    #- HaluEval

model: Med42

generation:
  few_shot: 3
  CoT: True
  k_self_consistency: 5 #set as False of do not want self-consistency
response:
  
  chosen_datasets:
  # Uncomment the datasets you would lPubMedQAike to evaluate 

   #MMLU_biology: "responses/{{ model }}/MMLU_biology" 144
   #MMLU_anatomy: "responses/{{ model }}/MMLU_anatomy" 135
   #MMLU_medicine: "responses/{{ model }}/3-shot/MMLU_medicine" 173
   #MMLU_clinical: "responses/{{ model }}/MMLU_clinical" 265
   #PubMedQA: "responses/{{ model }}/PubMedQA"
   #MedMCQA: "responses/{{ model }}/MedMCQA"

shortened: shortened/Meditron
